### PR TITLE
Fish completions

### PR DESCRIPTION
**Pull request by jc00ke**
I've got more in the works, but wanted to get this out for discussion.

### CODE REVIEW

**Review by rlefevre — COMMENTED** [review]
Fish completions are very welcome, but please make at least `elm` completions complete before. 

This includes `elm install` with local packages completion.

**Comment by rlefevre** [comment]
Closing because this draft PR seems inactive.

**Comment by jc00ke** [comment]
I'll see if I can find some time soon to finish this. Fish completions are trickier than I first imagined.

**Comment by rlefevre** [comment]
Sure, no hurry. Just reopen when you're ready.

**Pull request closed without merging**
